export const iconsObj = {
  '01d': require('../assets/icons/wheather/01d.png'),
  '01n': require('../assets/icons/wheather/01n.png'),
  '02d': require('../assets/icons/wheather/02d.png'),
  '02n': require('../assets/icons/wheather/02n.png'),
  '03d': require('../assets/icons/wheather/03d.png'),
  '03n': require('../assets/icons/wheather/03n.png'),
  '04d': require('../assets/icons/wheather/04d.png'),
  '04n': require('../assets/icons/wheather/04n.png'),
  '09d': require('../assets/icons/wheather/09d.png'),
  '09n': require('../assets/icons/wheather/09n.png'),
  '10d': require('../assets/icons/wheather/10d.png'),
  '10n': require('../assets/icons/wheather/10n.png'),
  '11d': require('../assets/icons/wheather/11d.png'),
  '11n': require('../assets/icons/wheather/11n.png'),
  '13d': require('../assets/icons/wheather/13d.png'),
  '13n': require('../assets/icons/wheather/13n.png'),
  '50d': require('../assets/icons/wheather/50d.png'),
  '50n': require('../assets/icons/wheather/50n.png'),
};
