export default (icons = {
  LOGO: require('../assets/icons/logo.png'),
  SMALL_LOGO: require('../assets/icons/smallIcon.png'),
  BURGER_MENU: require('../assets/icons/burger.png'),
  //Menu icons
  MENU_MAIN: require('../assets/icons/menu.png'),
  MENU_CITY: require('../assets/icons/city.png'),
  MENU_HISTORY: require('../assets/icons/history.png'),
  MENU_EDU: require('../assets/icons/edu.png'),
  MENU_SPORT: require('../assets/icons/sport.png'),
  MENU_CULTURE: require('../assets/icons/culture.png'),
  MENU_ECONOMY: require('../assets/icons/economy.png'),
  MENU_PHOTOS: require('../assets/icons/photos.png'),
  MENU_GEO: require('../assets/icons/geo.png'),
  MENU_EXECUTIVE: require('../assets/icons/city_head.png'),
  MENU_ABOUT: require('../assets/icons/about.png'),
  MENU_INFO: require('../assets/icons/info.png'),
  MENU_EXIT: require('../assets/icons/exit.png'),
  MENU_NEWS: require('../assets/icons/news.png'),
  MENU_SETTINGS: require('../assets/icons/settings.png'),
  ICON_FB: require('../assets/icons/fb.png'),
  ICON_BE: require('../assets/icons/be.png'),
  ICON_INST: require('../assets/icons/inst.png'),
  ICON_MORE: require('../assets/icons/more.png'),
  ICON_ABOUT_APP: require('../assets/icons/aboutApp.png'),
  MODAL_CLOSE_BUTTON: require('../assets/icons/close.png'),
});
